name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Angular
        run: npx ng build

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Dar permisos y compilar APK
        run: |
          chmod +x android/gradlew
          cd android
          ./gradlew assembleDebug

      - name: Subir APK como resultado descargable
        uses: actions/upload-artifact@v6
        with:
          name: SaveGo-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
